tiagosiebler/ftx-api

README.md
package.json

Seems stable so far. Bumping to major release 1.

Bump to 1.0.0 for stable release

---

README.md
examples/ftxus.ts
package.json
src/util/requestUtils.ts
src/util/requestWrapper.ts
src/websocket-client.ts

Fixes #2. Try it out via the beta tag: `npm install ftx-api@1.0.1-beta.1`.

Add support for ftx.us

---

package.json
src/util/WsStore.ts
src/websocket-client.ts

Fixes #8. Try it out via the beta tag: `npm install ftx-api@1.0.5-beta.2`.

Fix topic matching in topic store

---

package.json
src/util/requestWrapper.ts

Try it out:
```
npm install ftx-api@1.0.7-beta.1
```

fix(#10): signature error for param-less non-GET requests

---

.gitignore
package.json
src/util/requestWrapper.ts

Fixes exception when using the client without API credentials.

Fix requests without api keys

---

.circleci/config.yml
README.md
test/ftxcom/private.test.ts
test/ftxcom/public.test.ts
test/ftxus/private.test.ts
test/ftxus/public.test.ts
test/response.util.ts

- Add simple integration tests for private endpoints.
- Updated readme with build state.

Expand integration tests

---

src/rest-client.ts

Relative issue https://github.com/tiagosiebler/ftx-api/issues/44

Fixed getFills request making 'orderId' nullable

---

package.json
src/rest-client.ts

issue https://github.com/tiagosiebler/ftx-api/issues/47

Fixed 'getPositions' with 'showAveragePrice=false'

---

package.json

v1.0.20: add undocumented dust endpoints

---

examples/websockets.ts
package.json
src/index.ts
src/rest-client.ts
src/types/rest.ts
src/types/websockets.ts
src/util/requestUtils.ts
src/util/requestWrapper.ts
src/util/typeGuards.ts
src/websocket-client.ts
test/ftxcom/private.test.ts

- add importable request types as interfaces
- improve ws heartbeat mechanism
- improve ws error handling
- type expansions
- type guards for ws events

Add request types as interfaces, improve ws heartbeat, improve ws error handling, expand types, add type guard for ws

---

tsconfig.json

Prevents something like #53 from happening again

update tsconfig to always use relative paths

---

package.json
src/rest-client.ts
src/types/rest.ts
src/types/websockets.ts
src/util/WsStore.ts
src/util/typeGuards.ts
src/websocket-client.ts
test/ftxcom/private.test.ts
test/ftxus/private.test.ts

v1.1.2: expand types for ws & rest clients (positions, balances)

---

package.json
src/types/websockets.ts
src/util/typeGuards.ts

v1.1.3: add ws type for account trade fill

---

package.json

v1.1.6: fix(#66) signed request with empty params

---

src/rest-client.ts
src/types/rest.ts

https://docs.ftx.com/#spot-margin endpoints should support start_time and end_time params.
Support is now available.
Added BorrowHistoryParams type, forwarded params to the requestWrapper
- [X ] I have tested my changes locally

borrow History supports params

---

.prettierrc
package-lock.json
package.json
src/rest-client.ts
src/websocket-client.ts

- time range params for borrow history
- cleaning in ws client & public ws store
- linting enhancement

v1.1.7: support time range params for borrow history

---

src/util/requestUtils.ts
src/websocket-client.ts

This PR adds an option for disabling the reconnect feature.

feature/ add reconnect option

---

package.json

v1.1.9: add option to disable automatic ws reconnect (#78)

---

package-lock.json
package.json
src/rest-client.ts
test/ftxcom/public.test.ts

Adds funding rate request params (mentioned in #79). Adds test.

v1.1.10: feat(#79) add funding rate params

---

src/rest-client.ts

Added get USD value snapshots endpoint
N/A

Added get USD value snapshots endpoint
